# .travis.yml
language: php

branches:
  only:
    - master
    - BP_7-0
    - BP_6-2

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^8.5
    - php: 7.1
      env: TYPO3_VERSION=^8.5

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  - export TYPO3_PATH_WEB="$PWD/.build/web"

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running phpcs";
    .build/bin/phpcs --standard=PSR2 -n Classes/
  - >
    echo "Installing npm modules";
    pushd Build;
    npm install && npm install grunt-cli;
    echo "Executing grunt";
    node_modules/.bin/grunt;
    popd

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
      if [ $? -eq 0 ]; then
        rm -rf Build/bower_components
        rm -rf Build/node_modules
        git reset --hard HEAD && git clean -fx
        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${TRAVIS_TAG} to TER"
        .build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
      fi;
    fi;
