# .travis.yml
sudo: false
language: php

php:
  - 7.2

env:
  - TYPO3_VERSION=^9
  - TYPO3_VERSION=^10

install:
  - composer require typo3/cms-core:${TYPO3_VERSION} --no-progress
  - git checkout composer.json

script:
  - >
    echo;
    echo "Unit tests";
    composer test:php:unit

  - >
    echo;
    echo "PHP lint";
    composer test:php:lint

jobs:
  include:
    - stage: quality
      php: 7.2
      script: ./.build/bin/php-cs-fixer --diff --dry-run -v fix

    - stage: deploy
      sudo: true
      if: branch = master AND fork = false AND type = push
      addons:
        ssh_known_hosts:
          - 185.243.134.79
      script:
        - >
          openssl aes-256-cbc -K $encrypted_068845507e9d_key -iv $encrypted_068845507e9d_iv -in Build/deploy_rsa.enc -out /tmp/deploy_rsa -d;
          eval "$(ssh-agent -s)";
          chmod 600 /tmp/deploy_rsa;
          ssh-add /tmp/deploy_rsa;
        - >
          curl -LO https://deployer.org/deployer.phar;
          sudo mv deployer.phar /usr/local/bin/dep;
          sudo chmod +x /usr/local/bin/dep;
        - >
          dep self-update;
        - >
          dep --file="./Build/deploy.php" deploy;

cache:
  directories:
    - $HOME/.composer/cache
