# .travis.yml
language: php

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7.2
      env: TYPO3_VERSION=^8.7

sudo: false

addons:
  ssh_known_hosts:
    - bootstrap-package.com
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms:${TYPO3_VERSION}
  - export TYPO3_PATH_WEB="$PWD/.build/web"

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running php-cs-fixer";
    .build/bin/php-cs-fixer --diff --dry-run -v fix
  - >
    echo "Installing node_modules";
    pushd Build;
    yarn install && npm install grunt-cli;
    echo "Executing grunt";
    node_modules/.bin/grunt;
    popd

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
      if [ $? -eq 0 ]; then
        openssl aes-256-cbc -K $encrypted_068845507e9d_key -iv $encrypted_068845507e9d_iv -in Build/deploy_rsa.enc -out /tmp/deploy_rsa -d;
        eval "$(ssh-agent -s)";
        chmod 600 /tmp/deploy_rsa;
        ssh-add /tmp/deploy_rsa;
        curl -LO https://deployer.org/deployer.phar;
        sudo mv deployer.phar /usr/local/bin/dep;
        sudo chmod +x /usr/local/bin/dep;
        dep self-update;
        dep --file="./Build/deploy.php" deploy;
      fi;
    fi;

notifications:
  slack:
    secure: fj3lIrSaDe0EzBu+Twng/3vz/Bn2bGtKhEA6hG2vBg1g+/n54l7uhzXjRWgMaI4gfwuBmDcJvPnG2EFweBuSJgQgxcXzCvScZ1Z4Xu+gAeCCCeuVJHsWE34erE86a5MeIAsDZhH2UG/MTOlpUqqdFCD59z5XA+E52LiyTp7QMi0=
    on_success: change
    on_failure: always
