# .travis.yml
language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - EXTENSIONKEY=bootstrap_package
  matrix:
    - TYPO3_BRANCH=master
    - TYPO3_BRANCH=TYPO3_7-6
  exclude:
    - php: 5.5
      env: TYPO3_BRANCH=master
    - php: 5.6
      env: TYPO3_BRANCH=master

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

before_script:
  - cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - composer install
  - mkdir -p typo3conf/ext
  - mv $EXTENSIONKEY typo3conf/ext/

script:
  - >
    echo;
    echo "Running php lint";
    find typo3conf/ext/$EXTENSIONKEY/ -name \*.php | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    typo3conf/ext/$EXTENSIONKEY/vendor/bin/phpcs --standard=PSR2 -n typo3conf/ext/$EXTENSIONKEY/Classes/
  - >
    echo "Installing npm modules";
    pushd typo3conf/ext/$EXTENSIONKEY/Build;
    npm install && npm install bower grunt-cli;
    echo "Installing bower dependencies";
    node_modules/.bin/bower install;
    echo "Executing grunt";
    node_modules/.bin/grunt;
    popd
